language: java

cache:
  directories:
  - $HOME/.m2

branches:
  only:
  - develop
  - /^v\d+\.\d+\.\d+$/

deploy:
  provider: script
  script: "mvn --settings .travis.settings.xml deploy -B"
  skip_cleanup: true
  on:
    tags: true
