language: java

cache:
  directories:
  - $HOME/.m2

branches:
  only:
  - develop
  - master

deploy:
  provider: script
  script: "mvn --setings .travis.settings.xml deploy -B"
  skip_cleanup: true
  on:
    tags: true
